services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

    command: >
      sh -c "
        alembic upgrade head &&
        python -c 'from src.db.utils.partition_manager import create_year_partitions; create_year_partitions()'
      "
    restart: "no"

  app:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file: .env
    expose:
      - "8000"
    command: >
      uvicorn src.fastAPI.app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

volumes:
  pgdata:
