"""init column_is_deleted

Revision ID: 665b553f86bf
Revises: 3559b590bdc5
Create Date: 2025-09-29 10:33:19.314594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '665b553f86bf'
down_revision: Union[str, Sequence[str], None] = '3559b590bdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_expenses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('general_expenses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('receipts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('transfers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('warehouse_expenses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_expenses', 'is_deleted')
    op.drop_column('transfers', 'is_deleted')
    op.drop_column('receipts', 'is_deleted')
    op.drop_column('general_expenses', 'is_deleted')
    op.drop_column('direct_expenses', 'is_deleted')
    # ### end Alembic commands ###
