"""init column_cost_category

Revision ID: db80af6c3a97
Revises: 665b553f86bf
Create Date: 2025-09-29 16:07:24.963108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db80af6c3a97'
down_revision: Union[str, Sequence[str], None] = '665b553f86bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_object',
    sa.Column('object_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name_metafata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.alter_column('direct_expenses', 'cost_category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('direct_expenses', 'is_deleted')
    op.drop_column('general_expenses', 'is_deleted')
    op.drop_column('receipts', 'is_deleted')
    op.drop_column('transfers', 'is_deleted')
    op.alter_column('warehouse_expenses', 'cost_category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('warehouse_expenses', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_expenses', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('warehouse_expenses', 'cost_category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('transfers', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('general_expenses', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('direct_expenses', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('direct_expenses', 'cost_category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('deleted_object')
    # ### end Alembic commands ###
